<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <Authors>Frank Gehann</Authors>
        <Description>A collection of Id algorithms for c#</Description>
        <RepositoryUrl>https://github.com/teian/Identifier</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageProjectUrl>https://github.com/teian/Identifier</PackageProjectUrl>
        <PackageReleaseNotes>Release notes at https://github.com/teian/Identifier/releases</PackageReleaseNotes>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>id, snowflake, identity</PackageTags>   
        <PackageVersion>1.0.0</PackageVersion>            
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.39" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="/"/>
        <None Include="../../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

</Project>
